Initial support for Arrow format
Paradigm4/SciDBR pull request #243
Opened 2022-03-02 17:49 UTC by mpeterson-p4

This branch adds support for AIO arrow format (off by default).

2022-03-04 16:47 UTC, ksens requested changes
@mpeterson-p4 

Looks solid overall. Added some minor review comments. 

Excited to start using this soon!

2022-03-04 16:47 UTC, ksens commented on R/utility.R
> +iquery = function(db, query, `return`=FALSE, binary=TRUE, arrow = FALSE,...)
Would be good to put in a check that user cannot supply both `binary=T` and `arrow=T`

2022-03-04 16:47 UTC, ksens commented on R/internal.R
> +#' Return a SciDB query experssion as a data frame
Minor: Typo in `expression`

2022-03-04 16:47 UTC, ksens commented on R/internal.R
> +#' @keywords internal
Will need to run Roxygen on the package so that the docs show up in the `man` directory.

2022-03-04 16:47 UTC, ksens commented on R/utility.R
> +iquery = function(db, query, `return`=FALSE, binary=TRUE, arrow = FALSE,...)
Could you add in a one-liner explaining the new `arrow` parameter?

2022-03-04 16:47 UTC, ksens commented on tests/a.R
> +  check(iris[, 1:4], iquery(db, x, return=TRUE, arrow=TRUE)[, a][, 1:4])
Github Actions test suite seems to be failing https://github.com/Paradigm4/SciDBR/runs/5395947761?check_suite_focus=true. Could you take a look? It seems `save` is being called instead of `aio_save`. 

We would want to keep the GA test suite in an all-passing state before merging the PR. 

On this note, once you have the GA test suite passing, it would be good if you can add some more `arrow` tests to check other data types... but this is of lower priority, and can be done additively later (since `arrow` return is turned off by default).

2022-03-06 00:48 UTC, rvernica commented on tests/a.R
> +  check(iris[, 1:4], iquery(db, x, return=TRUE, arrow=TRUE)[, a][, 1:4])
I committed some changes to the GA workflows in this [branch](https://github.com/Paradigm4/SciDBR/tree/arrow-testing) These changes add support for `aio_tools` to the test setup. Please merge them into this branch to fix the GA suite.

2022-03-07 23:34 UTC, mpeterson-p4 commented
Just saw Kriti's push - I'll move the changes I've made in response to his review to that branch tonight so we can fire off some tests.

2022-03-07 23:41 UTC, ksens commented
Thanks @mpeterson-p4 ! I was just trying to merge in @rvernica 's latest changes to see if that helped pass the GA test suite. Sorry if this creates more work on branch merging on your side.

2022-03-08 14:46 UTC, mpeterson-p4 commented
It looks like the CentOS tests are failing, but the Ubuntu tests are passing. It looks like I haven't pushed the change that doesn't test the Arrow case if AIO isn't enabled, so this looks to something in the test env.

2022-03-09 14:59 UTC, rvernica commented
I had a bug in my workflow update. I pushed another fix in [this branch](https://github.com/Paradigm4/SciDBR/tree/ga-shim-restart) Once merged, AIO is enabled in shim in both setups (Ubuntu & CentOS). There is no test job for the case where AIO is not enabled in Shim. 

If you want to fix you code so it works if AIO is not enabled, then I would do it before you merge my changes. 

If we want to also test for the case where AIO is not enabled, then we need update the workflow for this case. Let me know.

2022-03-10 00:01 UTC, ksens commented
@mpeterson-p4 

I do not think we need to run GA test-suite for the case when AIO is disabled -- we hardly use `save` option over `aio_save` in the field. I believe the `AIO=0` path was getting run because of the artifact that AIO was disabled in GA tests. 

If you agree, then we would not need:

> "the change that doesn't test the Arrow case if AIO isn't enabled"

Then, merging PR https://github.com/Paradigm4/SciDBR/pull/248 should get all tests passing on this branch (including the test for `iquery(..., arrow = T)`. 

Will let you take the call on this.

2022-03-17 23:04 UTC, merged