consolidate curl handle creation and add on-the-fly configurability
Paradigm4/SciDBR pull request #254
Opened 2022-12-13 19:43 UTC by CB-93

Fixes #253 

### Problem
* User would query the DB from a Domino Instance
* The query itself takes > 5 minutes to complete
* User observes an indefinite hang in the query (15+ minutes).
* When querying locally, expected behavior observed (successful response and data acquisition via the `/read_bytes` request)

### Solution
* Found that the DB connection was getting timed out, so even though the query does run completely server-side, the client won't know because the response can't get back to the user (which would lead to downstream acquisition via `/read_bytes` e.g.).
* Resolved by locally configuring SciDB-R with TCP keep-alive related options upon curl handle creation

The PR aims to make the solution more flexible and configurable user-side. Meant to be more accommodating to different network configurations or the unique need for certain curl options.

Default behavior would be retained, so no deployments would be directly affected by this PR.

Tests currently failing because of some failure to install R (likely linked to the actions issue where the workflow automatically changed the version of the ubuntu machine it would run? Please correct me otherwise).

#### Side Note
as I let the customer know of this solution, Customer B's UI contractor suggested implementing an `async` approach for longer running queries, while discouraging the forcing open of connections as a long term solution. Integrating this approach now would be potentially tricky/take longer to do (e.g. I wouldn't want to `async` for quick queries, but finding out how big a query would be (proxy for query time) without querying the data itself -- whether by `show` or `summarize` -- would be non-trivial, so the user would have to know beforehand and perhaps set an `async` parameter.) Something to opine on later...

2022-12-13 19:52 UTC, agvandervelde requested changes

2022-12-13 19:52 UTC, agvandervelde commented on R/internal.R
> -                                ssl_verifypeer=0, post=TRUE, http_version=2, postfieldsize=length(data),
`postfieldsize` and `postfields` need special handling here.

2022-12-13 19:52 UTC, agvandervelde commented on R/internal.R
> -  handle_setheaders(h, .list=list(Authorization=digest_auth(db, "GET", uri)))
Some of those are POST and others are GET

2022-12-13 19:52 UTC, agvandervelde commented on R/internal.R
> -    handle_setheaders(h, .list=list(Authorization=digest_auth(db, "POST", uri)))
"POST"

2022-12-13 19:52 UTC, agvandervelde commented on R/internal.R
> +create_curl_handle <- function(db, uri){
You probably want to add a few arguments here to account for diversity in current calls.

2022-12-13 20:41 UTC, agvandervelde requested changes

2022-12-13 20:41 UTC, agvandervelde commented on R/internal.R
> +      valid = T
small note on style: `T` -> `TRUE`, `F` -> `FALSE`

2022-12-13 20:41 UTC, agvandervelde commented on R/internal.R
> +#' @keywords internal
If we're adding documentation, might as well document `@param`s and `@return`s.

2022-12-13 20:41 UTC, agvandervelde commented on R/internal.R
> +    ssl_verifypeer=0,
probably make this an option too, with default == 0

2022-12-14 17:37 UTC, agvandervelde commented on R/internal.R
> +        glue::glue(
@CB-93 it might be better to turn this into a `paste0`, to avoid adding `glue` as a dependency.

2022-12-14 19:36 UTC, agvandervelde approved these changes

2022-12-14 19:39 UTC, agvandervelde requested changes

2022-12-14 19:39 UTC, agvandervelde commented on R/internal.R
> +    ssl_verifypeer=as.integer(getOption("scidb.verifypeer", FALSE)),
Oh, the default here needs to be `0`, not `FALSE`.

2022-12-14 21:21 UTC, agvandervelde commented on R/internal.R
> +    ssl_verifypeer=as.integer(getOption("scidb.verifypeer", FALSE)),
ok, makes sense.

2022-12-15 15:21 UTC, agvandervelde approved these changes

2022-12-16 20:11 UTC, apoliakov approved these changes
Hey guys, this looks good. Thanks for the work!

2022-12-21 06:39 UTC, ksens requested changes
LGTM... Tests seem to be passing after merging master to this branch. 

Only change requested - update DESCRIPTION and NEWS files with details of a bumped package version number.

2023-01-04 11:27 UTC, merged